# -*- coding: utf-8 -*-
"""Employee attrition analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNZTnsU0bDC1B7oasnNSVw4m_WYHOOrQ
"""

# Importing necessary Libraries for Analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Attrition data.csv')
df.head() # to display first 5 rows of data

df.info()

"""# New Section"""

df.columns

df.shape # to get total no of rows and columns.

"""There are 29 columns and 4410 rows."""

df.describe()  # shows the statistical summary of data having numerical features.

df.isnull().sum()  # to know how many null values are present in each columns.

"""We can see there are certain null values in 'Number of Companies Worked', 'Environment Satisfaction', 'Work life Balance', 'Job satisfaction.'. We will deal with these null values in next step"""

df['NumCompaniesWorked'] = df['NumCompaniesWorked'].fillna(df['NumCompaniesWorked'].mean())
df['NumCompaniesWorked'].isnull().sum()  # to fill the null values in the column with the mean of the column.

df['EnvironmentSatisfaction'] = df['EnvironmentSatisfaction'].fillna(df['EnvironmentSatisfaction'].mean())
df['EnvironmentSatisfaction'].isnull().sum()

df['JobSatisfaction'] = df['JobSatisfaction'].fillna(df['JobSatisfaction'].mean())
df['JobSatisfaction'].isnull().sum()

df['WorkLifeBalance'] = df['WorkLifeBalance'].fillna(df['WorkLifeBalance'].mean())
df['WorkLifeBalance'].isnull().sum()

df.isnull().sum()

"""All the null values have been Filled."""

df.to_csv('CleanedAttritionData.csv')

"""Saving the cleaned data for further dashboard Creation."""

print(df['Attrition'].count())
df['Attrition'].value_counts().to_frame().reset_index()

"""We can see there were total 4410 Employees and out of them 711 has Attritioned and 3699 are lest in the company."""

features = ['Age',
       'DistanceFromHome',
       'MonthlyIncome',
       'PercentSalaryHike',
       'TotalWorkingYears', 'YearsWithCurrManager', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']

df[features].corr(numeric_only=True)  # Finding if there are any important correlations are present

"""We can see there are no major Correlations there."""

plt.figure(figsize=(15,12))

for i, feature in enumerate(features, 1):  # Looping all the columns with numerical data and comparing them with attrition data to find some insights
    plt.subplot(3,3,i)
    sns.histplot(data=df, x=feature, hue='Attrition', multiple='stack', kde=True)

plt.tight_layout()

"""As we can see from the above charts that Age, Total working Years of an Employee, Years at current Company, and Monthly Income have affected the Attrition rate the most. Employees who have less working Expirience and have been with the company for comparitively less period of time are more likely to be Attritioned. Also most of the Employees between the age of 25 to 35 have left the company.
Percentage of salary hike is also one of the factor that's leading the employees Attrition.
"""

feature1 = ['BusinessTravel', 'Department',
       'Education',
       'Gender', 'JobLevel', 'MaritalStatus']

plt.figure(figsize=(18,6))
sns.countplot(data=df, hue='Attrition', x='JobRole')
plt.figure(figsize=(15,6))
sns.countplot(data=df, hue='Attrition', x='EducationField')

plt.figure(figsize=(18,15))

for i, feature in enumerate(feature1, 1):   # Plotting all the Categorical Data.
    plt.subplot(3,3,i)
    sns.countplot(data=df, hue='Attrition', x=feature)

"""We can see from the above analysis that Employees from the field of Life Sciences and Medical are more likely to Attrition

Employees from The department of Research & Development having the job role of Research Scientist and Sales having the job role of Sales Executive are attritioning more. Library technician are also likely to attrition.

Employees who rarely get to travel rarely or comparitively less are leaving the company.

Gender and Marital Status are also the factors having more single male leaving the Company
"""

feature2 = ['StockOptionLevel', 'EnvironmentSatisfaction',
            'JobInvolvement', 'PerformanceRating', 'WorkLifeBalance', 'JobSatisfaction']

plt.figure(figsize=(18,15))

for i, feature in enumerate(feature2, 1):
    plt.subplot(3,3,i)
    sns.countplot(data=df, hue='Attrition', x=feature)

"""From the Chat Charts, We can conclude that:

Performance Rating plays an important factor here as employee with less rating has left the company significantly.

Stock option is also important here as employees with less than 2 stock Options are more likely to leave the company.
"""

